### ISSUE TITLE
metadata section in project pages

### ISSUE THREAD

**Issue by zachkrall** [zachkrall/krall-website#4]
**.yml**

```
artinfo:
  date: 2015
  media: Inkjet
  dims: 18 x 24 inches
```

**.html**

```
<table>
{% for item in page.artinfo %}
<tr><td>{{item title}}</td><td>{{item info}}></td> <!-- still need to figure this out -->
{% endfor %}
</table>
```
